---
title: "TB Patient Flows Modelling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(lubridate)
library(brms)
library(tidybayes)
library(parallel)

source("https://raw.githubusercontent.com/nbanho/helper/refs/heads/main/R/plotting.R")
source("https://raw.githubusercontent.com/nbanho/helper/refs/heads/main/R/formatting.R")
```

## Check convergence of simulation results

```{r check convergence}
# files for one day
sim_files <- list.files(
  "modelling-results/uncertain_all_equal_infectious/2024-06-26/",
  pattern = ".csv$", full.names = TRUE
)

# compute expected infections per simulation
sim_daily_inf <- map_dfr(sim_files, function(file) {
  read_csv(file) %>%
    mutate(
      sim = as.integer(str_extract(basename(file), "(?<=_sim_)\\d+")),
      risk = 1 - exp(-conc_diffusion)
    ) %>%
    group_by(sim) %>%
    summarise(exp_inf = sum(risk)) %>%
    ungroup()
})

# plot convergence
sim_daily_inf %>%
  ggplot(aes(x = sim, y = exp_inf)) +
  geom_point() +
  geom_segment(aes(yend = 0, xend = sim))
cumquantile <- function(x, p = .5) {
  purrr::map_dbl(seq_along(x), ~ quantile(x[1:.x], p))
}
conv_pl <- sim_daily_inf %>%
  arrange(sim) %>%
  mutate(
    median = cumquantile(exp_inf, .5),
    lower = cumquantile(exp_inf, .25),
    upper = cumquantile(exp_inf, .75),
    lower_80 = cumquantile(exp_inf, .1),
    upper_80 = cumquantile(exp_inf, .9),
    lower_95 = cumquantile(exp_inf, .025),
    upper_95 = cumquantile(exp_inf, .975)
  ) %>%
  ggplot(aes(x = sim)) +
  geom_line(aes(y = median)) +
  geom_line(aes(y = lower, color = "50%-CrI"), linetype = "dashed") +
  geom_line(aes(y = upper, color = "50%-CrI"), linetype = "dashed") +
  geom_line(aes(y = lower_80, color = "80%-CrI"), linetype = "dashed") +
  geom_line(aes(y = upper_80, color = "80%-CrI"), linetype = "dashed") +
  geom_line(aes(y = lower_95, color = "95%-CrI"), linetype = "dashed") +
  geom_line(aes(y = upper_95, color = "95%-CrI"), linetype = "dashed") +
  scale_y_log10(name = "Estimated number of Mtb infections") +
  scale_x_continuous(
    name = "Number of simulations",
    expand = expansion(mult = c(0, 0.01)), limits = c(1, NA)
  ) +
  scale_color_brewer(name = "Credible interval", type = "qual", palette = 1) +
  theme_custom() +
  theme(legend.title = element_blank())
save_plot(
  conv_pl,
  "results/modelling_convergence.png",
  w = 16, h = 10
)
```


## Risk of infection

### Daily risk

```{r risk over time}
# person features
person_df <- read_csv("data-clean/tracking/person-features.csv")

# modelling results
data_dir <- "modelling-results/uncertain_all_equal_infectious/"
folders <- list.dirs(data_dir, recursive = FALSE, full.names = TRUE)
files <- list.files(folders, pattern = "\\.csv$", full.names = TRUE)
daily_person_risk_df <- mclapply(files, function(f) {
  # simulation and date
  sim <- as.integer(str_extract(basename(f), "(?<=_sim_)\\d+"))
  date <- basename(dirname(f))

  # modelling result
  df <- read_csv(f) %>%
    mutate(sim = sim, date = as.Date(date)) %>%
    filter(hour_idx < 12) %>%
    left_join(
      person_df,
      by = c("new_track_id", "date")
    ) %>%
    mutate(
      risk_diffusion = 1 - exp(-conc_diffusion),
      risk_mixed = 1 - exp(-conc_mixed)
    ) %>%
    group_by(sim, date, female, healthcare_worker) %>%
    summarise(
      infections_diffusion = sum(risk_diffusion),
      infections_mixed = sum(risk_mixed),
      duration = sum(duration)
    ) %>%
    ungroup() %>%
    dplyr::select(date, sim, everything())
  return(df)
}, mc.cores = 6)
daily_person_risk_df <- do.call(rbind, daily_person_risk_df)

# add interventions and weekdays
interventions <- read_csv("data-clean/mapping_dates_interventions.csv") %>%
  mutate(
    date = as.Date(date),
    study_phase = factor(
      study_phase,
      levels = c("Baseline", "First intervention", "Second intervention")
    )
  )
daily_person_risk_df <- daily_person_risk_df %>%
  left_join(interventions, by = "date") %>%
  mutate(
    weekday = weekdays(date, abbreviate = TRUE),
    weekday = factor(
      weekday,
      levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
    )
  )

# compute infection rates
daily_risk_df <- daily_person_risk_df %>%
  group_by(sim, date, study_phase, weekday) %>%
  summarise(
    infections_diffusion = sum(infections_diffusion),
    infections_mixed = sum(infections_mixed),
    duration = sum(duration)
  ) %>%
  ungroup()

# daily average risk
avg_daily_risk <- daily_risk_df %>%
  group_by(date, study_phase) %>%
  summarise(
    median = median(infections_diffusion, na.rm = TRUE),
    lower = quantile(infections_diffusion, 0.025, na.rm = TRUE),
    upper = quantile(infections_diffusion, 0.975, na.rm = TRUE),
    lower_80 = quantile(infections_diffusion, 0.1, na.rm = TRUE),
    upper_80 = quantile(infections_diffusion, 0.9, na.rm = TRUE),
    lower_50 = quantile(infections_diffusion, 0.25, na.rm = TRUE),
    upper_50 = quantile(infections_diffusion, 0.75, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  arrange(date) %>%
  mutate(
    group = (study_phase != lag(study_phase)),
    group = ifelse(is.na(group), TRUE, group),
    group = cumsum(group),
    date = format(date, "%b %d"),
    date = factor(
      date,
      levels = unique(date)
    )
  )
avg_daily_risk %>%
  summarise(across(c(median, lower, upper), mean))
```

```{r plot daily infections over time}
# plot risk over time
risk_time_pl <- ggplot(
  data = avg_daily_risk,
  mapping = aes(x = date, colour = study_phase, group = group)
) +
  geom_linerange(
    data = avg_daily_risk,
    mapping = aes(ymin = lower, ymax = upper, alpha = "95%-CrI"),
    size = 2
  ) +
  geom_linerange(
    data = avg_daily_risk,
    mapping = aes(ymin = lower_80, ymax = upper_80, alpha = "80%-CrI"),
    size = 2
  ) +
  geom_linerange(
    data = avg_daily_risk,
    mapping = aes(ymin = lower_50, ymax = upper_50, alpha = "50%-CrI"),
    size = 2
  ) +
  geom_line(
    data = avg_daily_risk,
    mapping = aes(y = median),
    color = "black"
  ) +
  geom_point(
    data = avg_daily_risk,
    mapping = aes(y = median, fill = study_phase),
    color = "black", size = 1, shape = 21
  ) +
  scale_x_discrete(
    breaks = levels(avg_daily_risk$date)[
      seq(1, length(levels(avg_daily_risk$date)), by = 14)
    ],
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  scale_y_sqrt(
    name = "Expected number of Mtb infections",
    expand = c(0, 0),
    limits = c(0, NA)
  ) +
  scale_colour_manual(
    values = paletteer_d("colRoz::uluru"),
    name = "Study phase",
    labels = c(
      "Baseline",
      "1<sup>st</sup> intervention",
      "2<sup>nd</sup> intervention"
    )
  ) +
  scale_fill_manual(
    values = paletteer_d("colRoz::uluru"),
    name = "Study phase",
    labels = c(
      "Baseline",
      "1<sup>st</sup> intervention",
      "2<sup>nd</sup> intervention"
    )
  ) +
  scale_alpha_manual(
    values = c("95%-CrI" = 0.2, "80%-CrI" = 0.4, "50%-CrI" = 0.6),
    labels = c("95% quantile", "80% quantile", "50% quantile"),
    name = "Quantile"
  ) +
  theme_custom() +
  theme(
    legend.position = "bottom",
    legend.background = element_rect(
      fill = "white", color = "black", linewidth = 0.4
    ),
    legend.title = element_blank(), ,
    legend.direction = "horizontal",
    legend.text = element_markdown(margin = margin(l = -2)),
    legend.key.height = unit(.66, "lines"),
    legend.box = "horizontal",
    plot.margin = margin(r = 8, b = 8),
    axis.title.x = element_blank()
  ) +
  guides(
    alpha = guide_legend(order = 1),
    colour = guide_legend(order = 2),
    fill = "none"
  )
save_plot(
  risk_time_pl,
  "results/modelling_risk_per_day.png",
  w = 16, h = 10
)
```


### Total risk by model

```{r risk overall}
# overall risk
overall_risk_df <- daily_risk_df %>%
  group_by(sim) %>%
  summarise(
    total_infections_diffusion = sum(infections_diffusion),
    total_infections_mixed = sum(infections_mixed),
    total_difference = total_infections_diffusion - total_infections_mixed
  ) %>%
  ungroup() %>%
  pivot_longer(
    starts_with("total_"),
    names_to = "model",
    values_to = "infections"
  ) %>%
  pivot_wider(
    names_from = model,
    values_from = infections
  ) %>%
  arrange(desc(total_infections_diffusion)) %>%
  mutate(
    sim = 1:n()
  ) %>%
  pivot_longer(
    starts_with("total_"),
    names_to = "model",
    values_to = "infections"
  ) %>%
  mutate(
    model = recode_factor(
      model,
      "total_difference" = "**Difference: NUM – UM**<br>(proximity contribution)",
      "total_infections_mixed" = "**Uniform mixed model**<br>(UM: without proximity)",
      "total_infections_diffusion" = "**Non-uniform mixed model**<br>(NUM: with proximity)"
    )
  )

overall_risk_df %>%
  group_by(model) %>%
  summarise(
    median = median(infections),
    lower = quantile(infections, 0.025),
    upper = quantile(infections, 0.975)
  ) %>%
  mutate_if(is.numeric, ~ round_k(.x, 1))
```

```{r plot overall risk}
# plot
risk_difference_pl <- overall_risk_df %>%
  ggplot(aes(x = infections, y = model, color = model)) +
  tidybayes::stat_interval(
    aes(alpha = after_stat(level)),
    .width = c(.5, .8, .95),
    point_interval = median_qi
  ) +
  stat_summary(
    fun = median,
    geom = "point",
    color = "black",
    size = 2,
    shape = 23,
    fill = "white"
  ) +
  scale_x_continuous(
    name = "Expected number of Mtb infections",
    expand = expansion(mult = c(0, 0.01)),
    limits = c(0, NA)
  ) +
  scale_color_paletteer_d("wesanderson::AsteroidCity1") +
  scale_alpha_manual(
    values = c(0.2, 0.4, 0.6),
    labels = c("95% quantile", "80% quantile", "50% quantile"),
    name = "Quantile"
  ) +
  theme_custom() +
  theme(
    legend.position = "bottom",
    legend.background = element_rect(
      fill = "white", color = "black", linewidth = 0.4
    ),
    legend.title = element_blank(), ,
    legend.direction = "horizontal",
    legend.key.height = unit(.66, "lines"),
    legend.box = "horizontal",
    plot.margin = margin(r = 8, b = 8),
    axis.text.y = element_markdown(),
    axis.title.y = element_blank()
  ) +
  guides(
    alpha = guide_legend(order = 1, reverse = TRUE),
    colour = "none",
    fill = "none"
  )

save_plot(
  risk_difference_pl,
  "results/modelling_risk_overall.png",
  w = 16, h = 7
)
```


## Intervention effects

### Person-time adjusted rate ratio

```{r adjusted rate ratio}
# adjusted rate ratio per day
daily_risk_df <- daily_risk_df %>%
  mutate(
    adjusted_rate_ratio = (infections_diffusion + 1e-3) /
      (infections_mixed + 1e-3) / (duration / 3600),
    date2 = format(date, "%b %d"),
    date2 = factor(date2, levels = unique(date2))
  )

# plot adjusted rate ratio
rate_diff_pl <- ggplot(daily_risk_df,
  mapping = aes(x = date2, color = study_phase, y = adjusted_rate_ratio)
) +
  tidybayes::stat_interval(
    aes(alpha = after_stat(level)),
    .width = c(.5, .8, .95),
    point_interval = median_qi,
    size = 2
  ) +
  stat_summary(
    fun = median,
    geom = "point",
    color = "black",
    size = 1,
    shape = 23,
    fill = "white"
  ) +
  scale_x_discrete(
    breaks = levels(daily_risk_df$date2)[
      seq(1, length(levels(daily_risk_df$date2)), by = 14)
    ],
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  scale_y_continuous(
    name = "Person-time adjusted rate ratio (NUM/UM model, h⁻¹)",
  ) +
  scale_colour_manual(
    values = paletteer_d("colRoz::uluru"),
    name = "Study phase",
    labels = c(
      "Baseline",
      "1<sup>st</sup> intervention",
      "2<sup>nd</sup> intervention"
    )
  ) +
  scale_alpha_manual(
    values = c(0.2, 0.4, 0.6),
    labels = c("95% quantile", "80% quantile", "50% quantile"),
    name = "Quantile"
  ) +
  theme_custom() +
  theme(
    legend.position = "bottom",
    legend.background = element_rect(
      fill = "white", color = "black", linewidth = 0.4
    ),
    legend.title = element_blank(), ,
    legend.direction = "horizontal",
    legend.text = element_markdown(margin = margin(l = -2)),
    legend.key.height = unit(.66, "lines"),
    legend.box = "horizontal",
    plot.margin = margin(r = 8, b = 8),
    axis.title.x = element_blank()
  ) +
  guides(
    alpha = guide_legend(order = 1, reverse = TRUE),
    colour = guide_legend(order = 2),
    fill = "none"
  )

save_plot(
  rate_diff_pl,
  "results/modelling_adjusted_rate_ratio_per_day.png",
  w = 16, h = 11
)
```


### Estimated reduction in infections

```{r intervention effects}
# model per simulation
daily_risk_list <- daily_risk_df %>%
  split(.$sim)
risk_model <- brm_multiple(
  log1p(infections_diffusion) ~ offset(log1p(infections_mixed)) +
    offset(log(duration))
    + study_phase + weekday,
  data = daily_risk_list,
  family = gaussian(),
  chains = 4,
  cores = 1,
  iter = 500,
  seed = 12345,
  backend = "cmdstanr",
  silent = 2,
  recompile = FALSE
)
summary(risk_model)

# effect samples
estimated_reduction_df <- spread_draws(
  risk_model,
  b_study_phaseFirstintervention,
  b_study_phaseSecondintervention
) %>%
  mutate(b_study_phaseBaseline = 0) %>%
  pivot_longer(
    starts_with("b_"),
    names_to = "parameter",
    values_to = "value"
  ) %>%
  mutate(
    study_phase = recode_factor(parameter, !!!c(
      "b_study_phaseBaseline" = "Baseline",
      "b_study_phaseFirstintervention" = "First intervention",
      "b_study_phaseSecondintervention" = "Second intervention"
    )),
    reduction = 100 * (1 - exp(value))
  ) %>%
  group_by(study_phase) %>%
  summarise(
    median = median(reduction),
    lower = quantile(reduction, 0.025),
    upper = quantile(reduction, 0.975)
  )

estimated_reduction_df %>%
  mutate_if(is.numeric, ~ round_k(.x, 0))
```

```{r plot estimated reduction}
# plot
reduction_pl <- estimated_reduction_df %>%
  ggplot(aes(
    y = forcats::fct_rev(study_phase),
    color = study_phase
  )) +
  facet_wrap(~"Mtb infection risk") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_errorbar(
    aes(xmin = lower, xmax = upper),
    width = 0.1, size = 1
  ) +
  geom_point(
    aes(x = median),
    color = "black", size = cm(1), shape = 23, fill = "white"
  ) +
  scale_x_continuous(
    name = "Estimated reduction in the expected number of Mtb infections (%)",
    limits = c(0, NA)
  ) +
  scale_color_paletteer_d("colRoz::uluru") +
  theme_custom() +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none",
    plot.title.position = "plot"
  )

reduction_pl

saveRDS(
  reduction_pl,
  "results/modelling_estimated_reduction_in_infections.rds"
)
```


### Estimated prevented infections

```{r prevented infections}
# predict infections without interventions
new_data <- daily_risk_df %>%
  filter(study_phase != "Baseline") %>%
  mutate(
    study_phase = "Baseline",
    row_id = 1:n()
  )
pred_risk <- posterior_predict(
  risk_model,
  newdata = new_data,
  ndraws = 1000
) %>%
  expm1() %>%
  t()

# compute prevented infections
prev_inf <- pred_risk - new_data$infections_diffusion
prev_inf_df <- data.frame(prev_inf) %>%
  mutate(
    sim = new_data$sim,
    study_phase = daily_risk_df$study_phase[
      daily_risk_df$study_phase != "Baseline"
    ]
  ) %>%
  pivot_longer(
    -c(sim, study_phase),
    names_to = "sample",
    values_to = "prevented_infections"
  ) %>%
  group_by(study_phase, sim, sample) %>%
  summarise(
    prevented_infections = sum(prevented_infections)
  ) %>%
  ungroup()

prev_inf_df_summary <- prev_inf_df %>%
  group_by(study_phase) %>%
  summarise(
    median = median(prevented_infections),
    lower = quantile(prevented_infections, 0.025),
    upper = quantile(prevented_infections, 0.975)
  ) %>%
  ungroup() %>%
  bind_rows(
    prev_inf_df %>%
      group_by(sample, sim) %>%
      summarise(
        prevented_infections = sum(prevented_infections)
      ) %>%
      ungroup() %>%
      summarise(
        median = median(prevented_infections),
        lower = quantile(prevented_infections, 0.025),
        upper = quantile(prevented_infections, 0.975)
      ) %>%
      mutate(study_phase = "Total interventions")
  ) %>%
  mutate(
    study_phase = factor(
      study_phase,
      levels = c(
        "First intervention",
        "Second intervention",
        "Total interventions"
      )
    )
  )

prev_inf_df_summary %>%
  mutate_if(is.numeric, ~ round_k(.x, 0))
```

```{r plot prevented infections}
# plot
prevented_infections_pl <- prev_inf_df_summary %>%
  ggplot(aes(x = study_phase, y = median, fill = study_phase)) +
  geom_bar(stat = "identity") +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.2,
    color = "black",
    size = 1
  ) +
  scale_fill_manual(
    values = c(paletteer_d("colRoz::uluru")[2:3], "brown"),
    name = "Study phase"
  ) +
  scale_y_continuous(
    name = "Estimated expected number of Mtb infections prevented",
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_custom() +
  theme(
    axis.title.x = element_blank(),
    plot.title.position = "plot"
  )

save_plot(
  prevented_infections_pl,
  "results/modelling_prevented_infections.png",
  w = 12, h = 8
)
```


## Association with spatial density

```{r add spatial density measures}
# load spatial density data
files_occupancy <- list.files("data-clean/tracking/occupancy",
  pattern = "\\.csv$", full.names = TRUE
)
occupancy_df <- mclapply(files_occupancy, function(file) {
  data.table::fread(file) %>%
    mutate(date = as.Date(basename(file)))
}, mc.cores = 2)
occupancy_df <- do.call(rbind, occupancy_df)

# aggregate daily
daily_density_df <- occupancy_df %>%
  group_by(date) %>%
  summarise(
    gini = median(gini_kde, na.rm = TRUE),
    entropy = median(entropy_kde, na.rm = TRUE)
  ) %>%
  ungroup()

# standardise measures
daily_density_df <- daily_density_df %>%
  mutate(
    gini_z = scale(gini),
    entropy_z = scale(entropy)
  )

# add to infection risk data
daily_risk_df <- daily_risk_df %>%
  left_join(daily_density_df, by = "date")
```

```{r association spatial density gini}
# model gini
risk_gini_model <- brm_multiple(
  log1p(infections_diffusion) ~ offset(log1p(infections_mixed)) +
    offset(log(duration))
    + gini_z + weekday,
  data = split(daily_risk_df, daily_risk_df$sim),
  family = gaussian(),
  chains = 4,
  cores = 1,
  iter = 500,
  seed = 12345,
  backend = "cmdstanr",
  silent = 2,
  recompile = FALSE
)
summary(risk_gini_model)

# estimated effect
spread_draws(
  risk_gini_model,
  b_gini_z,
  ndraws = 1000
) %>%
  median_qi(b_gini_z) %>%
  mutate_if(is.numeric, ~ round_k(.x, 2))
```

```{r association spatial density entropy}
# model entropy
risk_entropy_model <- brm_multiple(
  log1p(infections_diffusion) ~ offset(log1p(infections_mixed)) +
    offset(log(duration)) + entropy_z + weekday,
  data = split(daily_risk_df, daily_risk_df$sim),
  family = gaussian(),
  chains = 4,
  cores = 1,
  iter = 500,
  seed = 12345,
  backend = "cmdstanr",
  silent = 2,
  recompile = FALSE
)
summary(risk_entropy_model)

spread_draws(
  risk_entropy_model,
  b_entropy_z,
  ndraws = 1000
) %>%
  median_qi(b_entropy_z) %>%
  mutate_if(is.numeric, ~ round_k(.x, 2))
```


## Sensitivity analyses: infectious assumptions

```{r risk by infectiousness}
# files
conf_more_infectious_files <- list.files(
  "modelling-results/uncertain_confirmed_more_infectious/",
  pattern = "\\.csv$", full.names = TRUE, recursive = TRUE
)
hiv_more_infectious_files <- list.files(
  "modelling-results/uncertain_hiv_more_infectious/",
  pattern = "\\.csv$", full.names = TRUE, recursive = TRUE
)

# read data with risks
read_number_of_infections <- function(f) {
  sim <- str_extract(basename(f), "(?<=_sim_)\\d+")
  date <- str_extract(basename(dirname(f)), "\\d{4}-\\d{2}-\\d{2}")
  df <- read_csv(f) %>%
    filter(hour_idx < 12) %>%
    mutate(risk_diffusion = 1 - exp(-conc_diffusion)) %>%
    summarise(infections = sum(risk_diffusion)) %>%
    mutate(sim = as.integer(sim), date = as.Date(date)) %>%
    dplyr::select(sim, date, infections)
  return(df)
}

# scenario risks
conf_more_infectious_df <- map_dfr(
  conf_more_infectious_files,
  read_number_of_infections
)
hiv_more_infectious_df <- map_dfr(
  hiv_more_infectious_files,
  read_number_of_infections
)

# combine
uncertain_df <- bind_rows(
  daily_risk_df %>%
    group_by(sim, date) %>%
    summarise(infections = sum(infections_diffusion)) %>%
    ungroup() %>%
    mutate(
      assumption =
        "**Main analysis**<br>All equal infectious"
    ),
  conf_more_infectious_df %>%
    mutate(
      assumption =
        "**Scenario 1**<br>Confirmed more infectious"
    ),
  hiv_more_infectious_df %>%
    mutate(
      assumption =
        "**Scenario 2**<br>HIV-positive more infectious"
    )
) %>%
  mutate(assumption = factor(assumption, levels = (unique(assumption)))) %>%
  group_by(sim, assumption) %>%
  summarise(infections = sum(infections)) %>%
  ungroup()

# summary
uncertain_df_summary <- uncertain_df %>%
  group_by(assumption) %>%
  summarise(
    median = median(infections),
    lower = quantile(infections, 0.025),
    upper = quantile(infections, 0.975)
  ) %>%
  ungroup()
uncertain_df_summary
```

```{r plot sensitivity analysis infectiousness}
sensitivity_pl <- uncertain_df %>%
  ggplot(aes(x = assumption, y = infections)) +
  geom_boxplot2(
    aes(fill = assumption)
  ) +
  geom_point(
    position = position_jitter(height = 0, width = .2),
    color = "black", size = 1, shape = 21
  ) +
  scale_y_continuous(
    name = "Estimated expected total number of new Mtb infections",
    expand = expansion(mult = c(0, 0.01)),
    limits = c(0, NA)
  ) +
  scale_fill_paletteer_d(
    "tvthemes::Bismuth"
  ) +
  theme_custom() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_markdown(),
    legend.position = "none"
  )


save_plot(
  sensitivity_pl,
  "results/modelling_risk_by_infectiousness_assumptions.png",
  w = 16, h = 12
)
```

```{r compare ratios}
# relative changes compared to all equal infectiousness
uncertain_ratio_df <- uncertain_df %>%
  filter(assumption != levels(assumption)[1]) %>%
  left_join(
    uncertain_df %>%
      filter(assumption == levels(assumption)[1]) %>%
      dplyr::select(sim, base_infections = infections),
    by = "sim"
  ) %>%
  mutate(
    infections_change = 100 * log(infections / base_infections)
  )
uncertain_ratio_df_summary <- uncertain_ratio_df %>%
  group_by(assumption) %>%
  summarise(
    median = median(infections_change),
    lower = quantile(infections_change, 0.025),
    upper = quantile(infections_change, 0.975)
  ) %>%
  ungroup() %>%
  mutate_if(is.numeric, ~ round_k(.x, 0))
uncertain_ratio_df_summary
```


## Stratification by gender and healtcare worker status

```{r}
# hourly risk by group
hourly_risk <- function(df, f = c(0, 1), h = c(0, 1)) {
  daily_person_risk_df %>%
    rename(hcw = healthcare_worker) %>%
    filter(!is.na(female), !is.na(hcw)) %>%
    filter(between(female, f[1], f[2])) %>%
    filter(between(hcw, h[1], h[2])) %>%
    group_by(sim) %>%
    summarise(
      infections = sum(infections_diffusion),
      duration = sum(duration)
    ) %>%
    ungroup() %>%
    mutate(rate = infections / duration * 3600)
}

hourly_risk_df <- bind_rows(
  hourly_risk(daily_person_risk_df) %>%
    mutate(group = "Overall"),
  hourly_risk(daily_person_risk_df, f = c(0, 0.5)) %>%
    mutate(group = "Males"),
  hourly_risk(daily_person_risk_df, f = c(0.5, 1)) %>%
    mutate(group = "Females"),
  hourly_risk(daily_person_risk_df, h = c(0, 0.5)) %>%
    mutate(group = "Healthcare workers"),
  hourly_risk(daily_person_risk_df, h = c(0.5, 1)) %>%
    mutate(group = "Non-healthcare workers")
) %>%
  mutate(
    group = factor(
      group,
      levels = c(
        "Overall", "Females", "Males",
        "Healthcare workers", "Non-healthcare workers"
      )
    )
  )

hourly_risk_df %>%
  group_by(group) %>%
  median_qi(1000 * rate) %>%
  mutate_if(is.numeric, ~ round_k(.x, 2))
```

```{r time till first infection}
hourly_risk_df %>%
  mutate(
    hours_till_infection = 1 / rate
  ) %>%
  group_by(group) %>%
  median_qi(hours_till_infection) %>%
  mutate_if(is.numeric, ~ round_k(.x, 0))
```

```{r boxplot infections by group}
# plot
hourly_risk_pl <- ggplot(hourly_risk_df,
  mapping = aes(x = group, y = rate, fill = group)
) +
  geom_boxplot2() +
  geom_point(
    position = position_jitter(height = 0, width = .2),
    shape = 21, fill = NA, color = "black", size = 1
  ) +
  scale_y_continuous(
    name = "Estimated Mtb infection rate (infections per 1,000 person-hours)",
    expand = expansion(mult = c(0.01, 0.01)),
    limits = c(0, NA),
    labels = function(x) round_k(1000 * x, 1)
  ) +
  theme_custom() +
  theme(
    axis.title.x = element_blank(),
    legend.position = "none"
  )

save_plot(
  hourly_risk_pl,
  "results/modelling_hourly_risk_by_group.png",
  w = 16, h = 12
)
```

```{r rate ratios by gender and healthcare workers}
# compare rate ratios
strat_ratio_df <- hourly_risk_df %>%
  dplyr::select(group, sim, rate) %>%
  pivot_wider(
    names_from = group,
    values_from = rate
  ) %>%
  mutate(
    ratio_gender = log(Females / Males),
    ratio_hcw = log(`Healthcare workers` / `Non-healthcare workers`)
  ) %>%
  dplyr::select(sim, ratio_gender, ratio_hcw) %>%
  pivot_longer(
    -sim,
    names_to = "comparison",
    values_to = "rate_ratio"
  ) %>%
  group_by(comparison) %>%
  summarise(
    median = median(rate_ratio),
    lower = quantile(rate_ratio, 0.025),
    upper = quantile(rate_ratio, 0.975),
    pr = mean(rate_ratio > 0)
  ) %>%
  mutate_if(is.numeric, ~ round_k(100 * .x, 0))

strat_ratio_df
```