---
title: "Person tracking data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(lubridate)
library(tidybayes)
library(parallel)
library(brms)

source("https://raw.githubusercontent.com/nbanho/helper/refs/heads/main/R/plotting.R")
source("https://raw.githubusercontent.com/nbanho/helper/refs/heads/main/R/formatting.R")
```

```{r load data}
# files
files <- list.files("data-clean/tracking/occupancy",
  pattern = "\\.csv$", full.names = TRUE
)

# load data
occupancy_df <- mclapply(files, function(file) {
  data.table::fread(file) %>%
    mutate(date = as.Date(basename(file)))
}, mc.cores = 2)

# add weekday
occupancy_df <- do.call(rbind, occupancy_df) %>%
  mutate(
    weekday = weekdays(date, abbreviate = TRUE),
    weekday = factor(
      weekday,
      levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
    )
  )

# add interventions
interventions <- read_csv("data-clean/mapping_dates_interventions.csv") %>%
  mutate(
    date = as.Date(date),
    study_phase = factor(
      study_phase,
      levels = c("Baseline", "First intervention", "Second intervention")
    ),
    study_phase_2 = if_else(
      study_phase %in% c("First intervention", "Second intervention"),
      study_phase, if_else(date > as.Date("2024-07-01"),
        "Post-intervention baseline", "Pre-intervention baseline"
      )
    ),
    study_phase_2 = factor(
      study_phase_2,
      levels = c(
        "Pre-intervention baseline",
        "First intervention",
        "Second intervention",
        "Post-intervention baseline"
      )
    )
  )
occupancy_df <- occupancy_df %>%
  left_join(interventions, by = "date")

# entries
counts_df <- data.table::fread("data-clean/tracking/counts/counts.csv") %>%
  mutate(date = as.Date(from)) %>%
  filter(date %in% unique(occupancy_df$date))

# track durations
track_times_df <- data.table::fread(
  "data-clean/tracking/time-in-clinic.csv"
) %>%
  mutate(date = as.Date(date)) %>%
  left_join(interventions, by = "date")
```


## Descriptive summaries

```{r person visits and movements}
# number of entries
entries_df <- counts_df %>%
  filter(name == "entry_main") %>%
  filter(type == "fw") %>%
  group_by(date) %>%
  summarise(n = sum(count, na.rm = TRUE)) %>%
  ungroup()
sprintf("Number of visits: %i", sum(entries_df$n))

entries_df %>%
  summarise(
    median_n = median(n, na.rm = TRUE),
    low_n = quantile(n, 0.25, na.rm = TRUE),
    upper_n = quantile(n, 0.75, na.rm = TRUE)
  ) %>%
  mutate_all(~ scales::comma(round(.x, 0)))
entries_df %>%
  left_join(interventions, by = "date") %>%
  group_by(study_phase_2) %>%
  summarise(
    median_n = median(n, na.rm = TRUE),
    low_n = quantile(n, 0.25, na.rm = TRUE),
    upper_n = quantile(n, 0.75, na.rm = TRUE)
  ) %>%
  mutate_if(is.numeric, ~ scales::comma(round(.x, 0)))

# number of movements
sprintf("Number of movements: %i", nrow(track_times_df))
track_times_df %>%
  group_by(date) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  summarise(
    median_n = median(n, na.rm = TRUE),
    low_n = quantile(n, 0.25, na.rm = TRUE),
    upper_n = quantile(n, 0.75, na.rm = TRUE)
  ) %>%
  mutate_all(~ scales::comma(round(.x, 0)))
track_times_df %>%
  group_by(study_phase_2, date) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  group_by(study_phase_2) %>%
  summarise(
    median_n = median(n, na.rm = TRUE),
    low_n = quantile(n, 0.25, na.rm = TRUE),
    upper_n = quantile(n, 0.75, na.rm = TRUE)
  ) %>%
  mutate_if(is.numeric, ~ scales::comma(round(.x, 0)))

# track duration
track_times_df %>%
  summarise(
    median_time = median(duration, na.rm = TRUE),
    low_time = quantile(duration, 0.25, na.rm = TRUE),
    upper_time = quantile(duration, 0.75, na.rm = TRUE)
  ) %>%
  mutate_all(~ round(.x / 60, 1))
track_times_df %>%
  group_by(study_phase_2) %>%
  summarise(
    median_time = median(duration, na.rm = TRUE),
    low_time = quantile(duration, 0.25, na.rm = TRUE),
    upper_time = quantile(duration, 0.75, na.rm = TRUE)
  ) %>%
  mutate_if(is.numeric, ~ round(.x / 60, 1))
```


## Occupancy over time

```{r occupancy over time}
daytime_occupancy_df <- occupancy_df %>%
  group_by(time) %>%
  summarise(
    mid = median(N, na.rm = TRUE),
    .lower = quantile(N, 0.25, na.rm = TRUE),
    .upper = quantile(N, 0.75, na.rm = TRUE)
  ) %>%
  ungroup()
weekday_occupancy_df <- occupancy_df %>%
  group_by(weekday, time) %>%
  summarise(mid = mean(N, na.rm = TRUE)) %>%
  ungroup()
peak_occupancy_df <- occupancy_df %>%
  group_by(date) %>%
  summarise(peak = max(N, na.rm = TRUE)) %>%
  ungroup()
peak_annotation <- paste0(
  "Daily peak: ", round_k(median(peak_occupancy_df$peak), 0), " people",
  " (IQR ", round_k(quantile(peak_occupancy_df$peak, 0.25), 0), "-",
  round_k(quantile(peak_occupancy_df$peak, 0.75), 0), ")"
)


occupancy_pl <- ggplot(mapping = aes(x = time)) +
  geom_ribbon(
    data = daytime_occupancy_df,
    mapping = aes(ymin = .lower, ymax = .upper),
    alpha = .4, fill = "grey50"
  ) +
  geom_line(
    data = weekday_occupancy_df,
    mapping = aes(y = mid, group = weekday, color = weekday),
    size = .2, alpha = .8
  ) +
  geom_line(
    data = daytime_occupancy_df,
    mapping = aes(y = mid),
    size = .2, alpha = .8, color = "black"
  ) +
  # annotate(
  #   "text",
  #   x = 3600 * 12, y = max(weekday_occupancy_df$mid),
  #   label = peak_annotation,
  #   hjust = 1.025, vjust = 2, size = 8 / cm(1)
  # ) +
  scale_y_continuous(
    name = "Number of people in waiting area",
    limits = c(0, NA),
    expand = expansion(mult = c(0, 0.01))
  ) +
  scale_x_continuous(
    name = "Daytime (hour)",
    breaks = seq(0, 3600 * 12, by = 3600),
    labels = function(x) paste(floor(x / 3600) + 6, ":00", sep = ""),
    limits = c(0, 3600 * 12),
    expand = c(0, 0)
  ) +
  scale_color_manual(
    values = paletteer_d("colRoz::uluru"),
    breaks = levels(weekday_occupancy_df$weekday),
    name = "Weekday"
  ) +
  theme_custom() +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.99, 0.975),
    legend.justification = c(0.99, 0.975),
    legend.background = element_rect(
      fill = "white", color = "black", linewidth = 0.4
    ),
    legend.key.width = unit(.66, "lines"),
    legend.direction = "vertical",
    legend.box = "horizontal",
    legend.margin = margin(l = 3, t = 3, b = 3, r = 3),
    plot.margin = margin(r = 12)
  ) +
  guides(
    color = guide_legend(
      override.aes = list(linewidth = .66, order = 2), ncol = 1
    )
  )
occupancy_pl
saveRDS(occupancy_pl, "results/tracking_occupancy_over_time.rds")
```


## Density over time

```{r density over time}
daytime_density_df <- occupancy_df %>%
  mutate(
    across(c(gini_kde, entropy_kde), ~ ifelse(N <= 10, NA, .x))
  ) %>%
  dplyr::select(N, time, gini_kde, entropy_kde) %>%
  pivot_longer(
    cols = c(N, gini_kde, entropy_kde),
    names_to = "metric",
    values_to = "value"
  ) %>%
  group_by(time, metric) %>%
  summarise(
    mid = median(value, na.rm = TRUE),
    .lower = quantile(value, 0.25, na.rm = TRUE),
    .upper = quantile(value, 0.75, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    metric = factor(
      metric,
      levels = c("N", "gini_kde", "entropy_kde")
    )
  )

density_pl <- ggplot(
  filter(daytime_density_df, metric != "entropy_kde"), aes(x = time)
) +
  facet_wrap(~metric,
    ncol = 1, scales = "free_y",
    labeller = as_labeller(c(
      N = "Number of people in clinic waiting area\n(higher values mean more crowded)",
      gini_kde = "Gini coefficient\n(higher values mean more clustered)"
      # entropy_kde = "Entropy\n(higher values mean less clustered)"
    )),
    strip.position = "left"
  ) +
  geom_line(aes(y = mid), size = .2, alpha = .8, color = "black") +
  geom_ribbon(
    aes(ymin = .lower, ymax = .upper),
    alpha = .4, fill = "grey50"
  ) +
  scale_y_continuous(
    name = "Value",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    name = "Daytime (hour)",
    breaks = seq(0, 3600 * 12, by = 3600),
    labels = function(x) floor(x / 3600) + 6,
    expand = c(0, 0)
  ) +
  theme_custom() +
  theme(
    axis.title.y = element_blank(),
    strip.placement = "outside",
    strip.text = element_text(face = 1, margin = margin(r = 0)),
  )

save_plot(
  density_pl,
  "results/tracking_density_over_time.png",
  w = 16, h = 14
)
````


## Intervention effects on the Gini coefficient

```{r density by study phase}
# daily average occupancy
daily_density_df <- occupancy_df %>%
  group_by(date, weekday, study_phase) %>%
  summarise(
    entropy = median(entropy_kde, na.rm = TRUE),
    gini = median(gini_kde, na.rm = TRUE),
  ) %>%
  ungroup()

# values by study phase
daily_density_df %>%
  group_by(study_phase) %>%
  summarise(
    median_gini = median(gini, na.rm = TRUE),
    low_gini = quantile(gini, 0.25, na.rm = TRUE),
    upper_gini = quantile(gini, 0.75, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate_if(is.numeric, ~ round_k(.x, 2))

# plot distribution by study phase
ggplot(daily_density_df, aes(x = study_phase, y = gini)) +
  geom_boxplot() +
  geom_jitter(width = .1, height = 0, alpha = .5) +
  scale_y_continuous(
    name = "Spatial density (Gini coefficient)",
    expand = expansion(mult = c(0, 0.01))
  ) +
  scale_x_discrete(name = "Study phase") +
  theme_custom() +
  theme(
    axis.title.x = element_blank(),
    plot.margin = margin(r = 12)
  )

# model
gini_model <- brms::brm(
  gini ~ study_phase + weekday,
  data = daily_density_df,
  family = Beta(),
  iter = 500,
  chains = 4,
  cores = 1,
  seed = 12345
)
summary(gini_model)

# parameter samples
gini_effects_smpls <- spread_draws(
  gini_model,
  b_study_phaseFirstintervention,
  b_study_phaseSecondintervention
)
saveRDS(
  gini_effects_smpls,
  "results/tracking_gini_effects_samples.rds"
)

# summarise
density_reduction_df <- gini_effects_smpls %>%
  mutate(b_study_phaseBaseline = 0) %>%
  pivot_longer(
    starts_with("b_"),
    names_to = "parameter",
    values_to = "value"
  ) %>%
  mutate(
    study_phase = recode_factor(parameter, !!!c(
      "b_study_phaseBaseline" = "Baseline",
      "b_study_phaseFirstintervention" = "First intervention",
      "b_study_phaseSecondintervention" = "Second intervention"
    )),
    study_phase = factor(
      study_phase,
      levels = c("Baseline", "First intervention", "Second intervention")
    ),
    odds = exp(value),
    reduction = odds - 1,
    reduction = -100 * reduction
  ) %>%
  group_by(study_phase) %>%
  summarise(
    median = median(reduction),
    lower = quantile(reduction, 0.025),
    upper = quantile(reduction, 0.975)
  )

density_reduction_pl <- density_reduction_df %>%
  ggplot(aes(
    y = forcats::fct_rev(study_phase),
    x = median, color = study_phase
  )) +
  facet_wrap(~"Spatial clustering of people") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_errorbar(
    aes(xmin = lower, xmax = upper),
    width = 0.1, size = 1
  ) +
  geom_point(
    aes(x = median),
    color = "black", size = cm(1), shape = 23, fill = "white"
  ) +
  scale_x_continuous(
    name = "Estimated reduction in the Gini coefficient (%)",
    limits = c(0, NA)
  ) +
  scale_color_paletteer_d("colRoz::uluru") +
  theme_custom() +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none",
    plot.title.position = "plot"
  )

density_reduction_pl

saveRDS(
  density_reduction_pl,
  "results/modelling_estimated_reduction_in_spatial_density.rds"
)
```


## Intervention effects on Entropy

```{r entropy by study phase}
# overall density distribution
hist(daily_density_df$entropy)

# values by study phase
daily_density_df %>%
  group_by(study_phase) %>%
  summarise(
    median_entropy = median(entropy, na.rm = TRUE),
    low_entropy = quantile(entropy, 0.25, na.rm = TRUE),
    upper_entropy = quantile(entropy, 0.75, na.rm = TRUE)
  ) %>%
  ungroup()

# model
entropy_model <- brms::brm(
  entropy ~ study_phase + weekday,
  data = daily_density_df,
  family = gaussian(),
  iter = 500,
  chains = 4,
  cores = 1,
  seed = 12345
)
summary(entropy_model)

# parameter samples
entropy_effects_smpls <- spread_draws(
  entropy_model,
  b_study_phaseFirstintervention,
  b_study_phaseSecondintervention
)

# summarise
entropy_effects <- entropy_effects_smpls %>%
  pivot_longer(
    starts_with("b_"),
    names_to = "parameter",
    values_to = "value"
  ) %>%
  mutate(
    study_phase = case_when(
      parameter == "b_study_phaseFirstintervention" ~ "First intervention",
      parameter == "b_study_phaseSecondintervention" ~ "Second intervention"
    ),
    study_phase = factor(
      study_phase,
      levels = c("First intervention", "Second intervention")
    ),
  ) %>%
  group_by(study_phase) %>%
  summarise(
    median = median(value),
    lower = quantile(value, 0.025),
    upper = quantile(value, 0.975),
    lower_80 = quantile(value, 0.1),
    upper_80 = quantile(value, 0.9),
    lower_50 = quantile(value, 0.25),
    upper_50 = quantile(value, 0.75)
  ) %>%
  ungroup()

entropy_effects %>%
  mutate_if(is.numeric, ~ round_k(.x, 2))
```


## Track time distribution

```{r track time distribution}
track_time_cat_df <- track_times_df %>%
  mutate(
    time_cat = cut(
      duration,
      breaks = c(0, 1, 5, 15, 30, Inf) * 60,
      labels = c(
        "<1 min", "1-5 min", "5-15 min",
        "15-30 min", ">30 min"
      ),
      right = FALSE
    )
  ) %>%
  group_by(time_cat) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(
    prop = n / sum(n),
    n = format(n, big.mark = ","),
    label = paste0(n, " (", round_k(100 * prop, 0), "%)")
  )

duration_distr_pl <- ggplot(track_time_cat_df, aes(x = time_cat, y = prop)) +
  geom_bar(stat = "identity", fill = "grey50", color = "black", alpha = .8) +
  geom_text(aes(label = label), vjust = -0.5, size = 8 / cm(1)) +
  scale_y_continuous(
    name = "Proprtion of person movements (%)",
    expand = expansion(mult = c(0, 0.1)),
    labels = function(x) 100 * x
  ) +
  scale_x_discrete(name = "Duration of person movement") +
  theme_custom()
save_plot(
  duration_distr_pl,
  "results/tracking_duration_distribution.png",
  w = 14, h = 12
)
```